#-----------------------------------------
# Hugo NexT ä¸»é¢˜å‚æ•°é…ç½®
#-----------------------------------------

mainSections = [ "post" ]
yearFormat = "2006"
monthFormat = "01-02"
dateFormat = "2006-01-02"
timeFormat = "2006-01-02T15:04:05-07:00"

# é¡µé¢æ¨¡å¼ Muse | Mist | Pisces
scheme = "Gemini"
darkmode = true

author = "Direct-A"
subtitle = "a blog as a log"
description = "a blog as a log"
keywords = "Direct-A, ç¼–ç¨‹, åšå®¢, æ•™ç¨‹, ç¬”è®°"
# TODO
# å°†æ–‡ç« çš„æè¿°å†…å®¹ç”¨äºé¦–é¡µå±•ç¤ºï¼ˆæš‚æ—¶æœªå®ç°ï¼‰
excerptDesc = true
readMoreBtn = true
# åœ¨æ‰‹æœºç«¯æ˜¾ç¤ºå‡å°‘å¡«å……å’Œè¾¹è·
mobileLayoutEconomy = true

# è°·æ­Œç«™ç‚¹éªŒè¯
# Google Webmaster tools verification.
# See = https://developers.google.com/search
#googleSiteVerification = <verify_code>
# å¾®è½¯ Bing ç«™éªŒè¯
# Bing Webmaster tools verification.
# See = https://www.bing.com/webmasters
#bingSiteVerification = <verify_code>
# Yandex ç«™ç‚¹éªŒè¯
# Yandex Webmaster tools verification.
# See = https://webmaster.yandex.ru
#yandexSiteVerification = <verify_code>
# ç™¾åº¦ç«™ç‚¹éªŒè¯
# Baidu Webmaster tools verification.
# See = https://ziyuan.baidu.com/site
#baiduSiteVerification = <verify_code>

# æ•°å­¦å…¬å¼æ¸²æŸ“æ”¯æŒï¼Œå¯é€‰å€¼ï¼š mathjax, katex
#math = mathjax

# TODO
fancybox = false
# TODO
lazyload = false
# TODO
pangu = false

# AddThisæ–‡ç« åˆ†äº«åŠŸèƒ½
# æ›´å¤šä¿¡æ¯åŠé…ç½®è¯·å‚è€ƒï¼šhttps://www.addthis.com
# AddThis Share.
# See = https://www.addthis.com
#addThisId = <Your addthis>

# è‡ªå®šä¹‰ Logo ï¼ˆç›®å‰åªæ”¯æŒ Mist é¡µé¢æ¨¡å¼ï¼‰
#customLogo = "/imgs/hugo_next_logo.png"

# [customFilePath]
#sidebar = custom_sidebar.html
#footer = custom_footer.html
#style = /css/custom_style.css

[favicon]
icon = "/imgs/icons/favicon.ico"
small = "/imgs/icons/favicon-16x16.ico"
medium = "/imgs/icons/favicon-32x32.ico"
appleTouchIcon = "/imgs/icons/apple-touch-icon-57x57.png"

# çŸ¥è¯†å…±äº«å›½é™…è®¸å¯ 4.0
# æ›´å¤šä¿¡æ¯ï¼š https://creativecommons.org/about/cclicenses/
# Creative Commons 4.0 International License.
# See = https://creativecommons.org/about/cclicenses/
[creativeCommons]
# å¯é€‰é…ç½® by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
license = "by-nc-sa"
# å¯é€‰é…ç½® big | small
size = "small"
sidebar = true
post = true

[openGraph]
enable = true
# googlePlus = "<g+:profile_link>"

# [openGraph.twitter]
# creator = "<twitter:creator>"
# image = "<twitter:image>"
# site = "<twitter:site>"

# [openGraph.facebook]
# admins = "<fb:admin_id>"
# app_id = "<fb:app_id>"

# ---------------------------------------------------------------
# ç«™ç‚¹é¡¶éƒ¨è®¾ç½®
# ---------------------------------------------------------------

[menuSets]
icons = true
transition = true
badges = true

[readingProgress]
enable = true
# è¿›åº¦æ¡å¼€å§‹ä½ç½® left | right
start = "left"
# è¿›åº¦æ¡æ˜¾ç¤ºä½ç½® top | bottom
position = "top"
reversed = false
color = "#37c6c0"
height = "3px"

[bookmark]
enable = true
color = "#222"
# æ”¯æŒæ–¹å¼ auto | manual
save = "manual"

[githubBanner]
enable = false
permalink = "https://github.com/hugo-next"
title = "Follow me on GitHub"

# ---------------------------------------------------------------
# é¡µé¢ä¸»ä½“è®¾ç½®
# ---------------------------------------------------------------

# TODO æš‚æ—¶ä¸æ”¯æŒ
[bodyScrollbar]
overlay = false
stable = true

[textAlign]
# å¯é€‰å€¼ start | end | left | right | center | justify | justify-all | match-parent
desktop = "justify"
mobile = "justify"

[themeColor]
light = "#222"
dark = "#222"

# ---------------------------------------------------------------
# ä¾§è¾¹æ è®¾ç½®
# ---------------------------------------------------------------

[sidebar]
# ä¾§è¾¹æ ä¸é¡¶éƒ¨èœå•æ çš„åç§»åƒç´ å¤§å°ï¼ˆä»…ä½œç”¨äº Pisces | Gemini é¡µé¢æ¨¡å¼ï¼‰
offset = 12
padding = 18
# ä¾§è¾¹æ ä½ç½®ï¼Œå¯é€‰ï¼š left | right
position = "left"
# è‡ªå®šä¹‰ä¾§è¾¹æ çš„å®½åº¦ï¼Œé»˜è®¤é…ç½®å¦‚ä¸‹
# Muse | Mist = 320
# Pisces | Gemini = 240
width = 256
# ä¾§è¾¹æ çš„æ˜¾ç¤ºæ–¹å¼ï¼Œå¯é€‰å€¼ï¼š
#  - post    é»˜è®¤åœ¨æ–‡ç« é¡µé¢å±•å¼€æ˜¾ç¤º
#  - always  åœ¨æ‰€æœ‰é¡µé¢å±•å¼€æ˜¾ç¤º
#  - hide    ç‚¹å‡»ä¾§è¾¹æ æŒ‰é’®æ‰æ˜¾ç¤º
#  - remove  å®Œå…¨ä¸æ˜¾ç¤ºä¾§è¾¹æ 
display = "post"

[backTop]
enable = true
sidebar = false
scrollpercent = true

[avatar]
url = "/imgs/hugo_next_avatar.png"
rounded = true
rotated = true

[siteState]
basic = true
  [siteState.views]
  enable = true
  # ç»„ä»¶ç±»å‹ï¼Œå¯é€‰å€¼ä¸ºï¼š 51la, busuanzi
  # ä½¿ç”¨51laæ—¶éœ€è¦æ³¨å†Œè´¦å·ï¼šhttps://invite.51.la/1NUfGTS1?target=V6
  plugin = "busuanzi"

[socials]
social0 = "Github || https://github.com/Direct-A || fab fa-github"
social1 = "E-Mail || mailto:songyicheng0@gmail.com || fa fa-envelope"
social2 = "Twitter || https://twitter.com/01_days_ || fab fa-twitter"
# çŸ¥ä¹ || https://www.zhihu.com/people/lisenhui || fa fa-book
#Google || https://plus.google.com/yourname || fab fa-google
#FB Page || https://www.facebook.com/yourname || fab fa-facebook
#StackOverflow || https://stackoverflow.com/yourname || fab fa-stack-overflow
#YouTube || https://youtube.com/yourname || fab fa-youtube
#Instagram || https://instagram.com/yourname || fab fa-instagram
#Skype || skype:yourname?call|chat || fab fa-skype

[socialIcons]
enable = true
iconsOnly = false
transition = true

[linksSets]
# See = https://fontawesome.com/
icon = "fa fa-globe"
title = "å‹æƒ…é“¾æ¥"
# å¯é€‰å€¼ block | inline
layout = "inline"

[links]
link0 = "Hugo-NexT || https://gitee.com/hugo-next/hugo-theme-next"
# link1 = "å‡¡æ¢¦æ˜Ÿå°˜ç©ºé—´ç«™ || https://lisenhui.cn"

[toc]
enable = true
number = true
wrap = false
expandAll = false
maxDepth = 3


# ---------------------------------------------------------------
# ç«™ç‚¹åº•éƒ¨è®¾ç½®
# ---------------------------------------------------------------

[footer]
since = 2_019
powered = true
translate = false
# copyright =

[footer.icon]
name = "fa fa-heart"
animated = true
color = "#ff0000"

# å›½å†… ICP å¤‡æ¡ˆå’Œå…¬å®‰ç½‘å¤‡ä¿¡æ¯
# See = https://beian.miit.gov.cn, http://www.beian.gov.cn
[footer.beian]
enable = true
icp = "å†€ICPå¤‡2022004242å·-1"
provinceAbbr = "å†€"
gonganNum = 2_022_004_242

[footer.vendors]
enable = true
title = "å…¶ä»–äº‘æœåŠ¡"

[[footer.vendors.list]]
name = "memos"
link = "https://memos.direct-a.cn"
  [footer.vendors.list.image]
  url = "/imgs/vendors/memos.webp"
  width = 20

[[footer.vendors.list]]
name = "gitea"
link = "https://gitea.direct-a.cn"
  [footer.vendors.list.image]
  url = "/imgs/vendors/gitea.png"
  width = 20

# ---------------------------------------------------------------
# æ–‡ç« å‚æ•°è®¾ç½®
# ---------------------------------------------------------------

[postMeta]
itemText = true
created = true
categories = true
wordCount = true
readTime = true
expired = true
summary = true

[postMeta.updated]
enable = true
anotherDay = true

[postMeta.comments]
enable = true
# è¯„è®ºç»Ÿè®¡æ’ä»¶ï¼Œæš‚åªæ”¯æŒwalineå’Œwaline3
plugin = "waline3"

[postMeta.views]
enable = true
# é¡µé¢è®¿é—®ç»Ÿè®¡æ’ä»¶ï¼Œæ”¯æŒbusuanzi, waline, waline3
plugin = "waline3"

[postAlerts.info]
icon = "circle-info"
color = "#4A90E2"

[postAlerts.note]
icon = "bell"
color = "#17A2B8"

[postAlerts.help]
icon = "circle-question"
color = "#967ADC"

[postAlerts.error]
icon = "circle-xmark"
color = "#DC3545"

[postAlerts.warning]
icon = "triangle-exclamation"
color = "#F39C12"

[postAlerts.success]
icon = "circle-check"
color = "#32CD32"

[postAlerts.important]
icon = "circle-plus"
color = "#007BFF"

[postFooter]
endLineTip = "~ æˆ‘å¯æ˜¯æœ‰åº•çº¿çš„å“Ÿ ~"
tagIcon = true

[rewardSets]
enable = true
animation = true
comment = '<i class="fa-solid fa-mug-hot"></i>è¯·æˆ‘å–æ¯å’–å•¡å§ ãƒ¾(^â–½^*)))'
  [rewardSets.reward]
  wechatpay = "/imgs/wechat-pay.png"
  alipay = "/imgs/ali-pay.png"
  #paypal = /images/paypal.png
  #bitcoin = /images/bitcoin.png

[followMe]
#channel0 = Twitter || https://twitter.com/username || fab fa-twitter
#channel1 = Telegram || https://t.me/channel_name || fab fa-telegram
# channel2 = WeChat || /images/wechat_channel.jpg || fab fa-weixin
channel3 = "RSS || /atom.xml || fa fa-rss"

[postEdit]
enable = false
url = "https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name/"

[codeblock]
copyBtn = true
# æ”¯æŒæ ·å¼ç±»å‹ default | flat | mac
style = "mac"


# ---------------------------------------------------------------
# TODO
# å­—ä½“è®¾ç½®ï¼ˆæš‚æ—¶æœªå®ç°ï¼‰
# ---------------------------------------------------------------
[font]
enable = true
# Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
# host =

[font.global]
external = true
family = "Lato"
# size = 16

[font.headings]
external = true
# family = "Lato"
# size = 16

[font.title]
external = true
# family = "Lato"
# size = 16

[font.posts]
external = true
# family = "Lato"

[font.codes]
external = true
# family = "Lato"

# ---------------------------------------------------------------
# SEO è®¾ç½®
# ---------------------------------------------------------------

[exturl]
# Automatically add `target='_blank'` attribute in external URL.
enable = true
icon = true

# ---------------------------------------------------------------
# ç¬¬ä¸‰æ–¹æ’ä»¶å’ŒæœåŠ¡è®¾ç½®
# ---------------------------------------------------------------
# TODO
[quicklink]
enable = false
home = false
archive = false
delay = true
timeout = 3_000
priority = true

# ---------------------------------------------------------------
# è¯„è®ºåŠŸèƒ½è®¾ç½®
# ---------------------------------------------------------------

# è¯„è®ºç»„ä»¶è®¾ç½®ï¼Œæœ€å¤šæ”¯æŒ2ä¸ªæ˜¾ç¤º
[comments]
# å¼€å¯è¯„è®ºç»„ä»¶
enable = true
# è®¾ç½®é»˜è®¤ä½¿ç”¨çš„è¯„è®ºæ’ä»¶
# å¯é€‰å€¼ livere | waline | waline3 | utterances | artalk | giscus
active = "waline3"
# è®©ç”¨æˆ·è‡ªå·±é€‰æ‹©ä½¿ç”¨è¯„è®ºæ’ä»¶ç•™è¨€
# å¦‚æœè®¾ç½®ä¸º falseï¼Œå°†é‡‡ç”¨ active å‚æ•°çš„é‚£ä¸ªæ’ä»¶
storage = false
# TODO
# lazyload = false

# TODO
# è®¾ç½®ä½ è¦æ˜¾ç¤ºçš„2ä¸ªè¯„è®ºæ’ä»¶ï¼Œ`weight` æ•°å­—è¶Šå°è¶Šé å‰
# `name` å‚æ•°åå¯é€‰å€¼ livere | waline | utterances | artalk | giscus
[[comments.nav]]
name = "waline3"
title = "Waline"
color = "#27ae60"
weight = 2

[[comments.nav]]
name = "giscus"
title = "Giscus"
color = "#886ce4"
weight = 1

# Waline è¯„è®ºæ’ä»¶
# æ›´å¤šé…ç½®ä¿¡æ¯è¯·å‚è€ƒï¼šhttps://waline.js.org/
[waline3]
placeholder = "è¯·æ–‡æ˜å‘è¨€å“Ÿ ãƒ¾(â‰§â–½â‰¦*)o å¯ç”¨å¿«æ·é”®é€‰å–è¡¨æƒ…ç¬¦å·ï¼šğŸ˜€ğŸ˜„ğŸ˜ğŸ¥³ğŸ‘»ğŸ‘½ğŸ‘€ğŸš„ (Windowç³»ç»Ÿï¼šWin+.ï¼ŒMacç³»ç»Ÿï¼šControl+Command+Space)"
sofa = "å¿«æ¥å‘è¡¨ä½ çš„æ„è§å§ (â‰§âˆ€â‰¦)ã‚"
emoji = false
search = true
imgUploader = false
wordLimit = 200
requiredMeta = ['nick', 'mail']
reaction = true
reactionText = [ 'ç‚¹èµ', 'è¸©ä¸€ä¸‹', 'å¾—æ„', 'ä¸å±‘', 'å°´å°¬', 'ç¡è§‰']
reactionTitle = "ä½ è®¤ä¸ºè¿™ç¯‡æ–‡ç« æ€ä¹ˆæ ·ï¼Ÿ"
serverURL = "https://walinejs.comment.lithub.cc"

# Artalk è¯„è®ºæ’ä»¶
# æ›´å¤šé…ç½®ä¿¡æ¯è¯·å‚è€ƒï¼šhttps://artalk.js.org
#[artalk]
#site = "é»˜è®¤ç«™ç‚¹"
#placeholder = "è¯·æ–‡æ˜å‘è¨€ï¼Œè°¢è°¢ï¼"
#server = #<your artalk server url>

# LiveRe comments system
# You can get your uid from https://livere.com/
#[livere]
#uid = <your_uid>

# Utterances è¯„è®ºæ’ä»¶
# æ›´å¤šé…ç½®ä¿¡æ¯è¯·å‚è€ƒï¼šhttps://utteranc.es
#[utterances]
# Github ä»“åº“åœ°å€ï¼Œæ ¼å¼ï¼šç”¨æˆ·å/ä»“åº“åç§°
#repo = "username/repo-name"
# é—®é¢˜æ ‡é¢˜çš„æ¨¡å¼ï¼Œå¯é€‰å€¼ï¼špathname | url | title | og:title
#issueTerm = "pathname"
#label = "comments"
# ä¸»é¢˜å¯é€‰å€¼ï¼š github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
#theme = "preferred-color-scheme"

# Giscus è¯„è®ºæ’ä»¶
# æ›´å¤šé…ç½®ä¿¡æ¯è¯·å‚è€ƒï¼šhttps://giscus.app
[giscus]
repo = "username/repo-name"
#repoId = <repo-id>
category = "Comments"
#categoryId = <category-id>
reactions = false
emit = false
# è¯„è®ºè¾“å…¥æ¡†çš„ä½ç½®ï¼Œå¯é€‰å€¼ï¼š top | bottom
# Aavilable value = top | bottom
# è®¨è®ºåŒºå¸–å­æ ‡é¢˜ï¼Œå¯é€‰å€¼ï¼š pathname | url | title | og:title | è‡ªå®šä¹‰
# Available values = pathname | url | title | og:title | custom
mapping = "title"
# è¯„è®ºè¾“å…¥æ¡†çš„ä½ç½®ï¼Œå¯é€‰å€¼ï¼š top | bottom
# Aavilable value = top | bottom
inputPosition = "top"
# ä¸»é¢˜å¯é€‰å€¼ï¼š light | light_high_contrast | light_protanopia | light_tritanopia | dark | dark_high_contrast | dark_protanopia | dark_tritanopia | dark_dimmed | transparent_dark | preferred_color_scheme
theme = "preferred_color_scheme"

# ---------------------------------------------------------------
# æ–‡ç« å°ç»„ä»¶å’Œåˆ†äº«æœåŠ¡è®¾ç½®
# ---------------------------------------------------------------

# TODO
[rating]
enable = false
#id = <app_id>
color = "#fc6423"

[share]
enable = true
addtoany.locale = "zh-CN"
addtoany.num_services = 8

# ---------------------------------------------------------------
# ç«™ç‚¹ç»Ÿè®¡åŠŸèƒ½
# ---------------------------------------------------------------
# [analytics]
# 51La ç«™ç‚¹ç»Ÿè®¡
# æ›´å¤šä¿¡æ¯è¯·å‚è€ƒï¼šhttps://invite.51.la/1NUfGTS1?target=V6
#laId = <anaytics_id>
# ç™¾åº¦ç»Ÿè®¡
#baidu = <anaytics_id>
# è°·æ­Œç»Ÿè®¡
#google = <anaytics_id>

# ä¸è’œå­ç»Ÿè®¡
# For more information = http://ibruce.info/2015/04/04/busuanzi/
[analytics.busuanzi]
visitorsIcon = "fa fa-user"
viewsIcon = "fa fa-eye"

# ---------------------------------------------------------------
# å†…å®¹æœç´¢æœåŠ¡
# ---------------------------------------------------------------

# Algolia Search
# For more information = https://www.algolia.com
[algoliaSearch]
enable = false
#appId = <algolia app id>
#apiKey = <algolia api key>
#indexName = <algolia index name>
hits.perPage = 10
limit = 1_000

[localSearch]
enable = true
path = "/searchindexes.xml"
# æ˜¯ç«‹å³æœç´¢å½“è¾“å…¥å…³é”®å­—æ—¶ï¼Œå¯é€‰å€¼ auto | manual
trigger = "auto"
topNPerArticle = -1
unescape = false
preload = false
limit = 1_000

# ---------------------------------------------------------------
# åœ¨çº¿èŠå¤©æœåŠ¡
# ---------------------------------------------------------------

[chat]
enable = false
icon = "fa fa-comment"
text = "Chat"

# Gitter Support
# For more information = https://gitter.im
[gitter]
enable = false
room = "hugo-next/community"


# ---------------------------------------------------------------
# TODO
# æ ‡ç­¾è®¾ç½®ï¼ˆæš‚æ—¶æœªå®ç°ï¼‰
# ---------------------------------------------------------------

[note]
# Note tag style values:
#  - simple    bootstrap callout old alert style. Default.
#  - modern    bootstrap callout new (v2-v3) alert style.
#  - flat      flat callout style with background, like on Mozilla or StackOverflow.
#  - disabled  disable all CSS styles import of note tag.
style = "simple"
icons = true
lightBgOffset = 0

[tabs]
sticky = false

[tabs.transition]
tabs = false
labels = true

# PDF tag
# NexT will try to load pdf files natively, if failed, pdf.js will be used.
# So, you have to install the dependency of pdf.js if you want to use pdf tag and make it available to all browsers.
# Dependencies = https://github.com/next-theme/theme-next-pdf
[pdf]
enable = false
height = "500px"

# Mermaid tag
[mermaid]
enable = false

# Available themes = default | dark | forest | neutral
[mermaid.theme]
light = "default"
dark = "dark"

# ---------------------------------------------------------------
# åŠ¨ç”»æ•ˆæœè®¾ç½®
# ---------------------------------------------------------------

# é€šè¿‡ Animate.css å®ç°å¯¹æ•´ç«™çš„åŠ¨ç”»æ•ˆæœ
# For more information = https://animate.style
[motion]
enable = true
async = true

# All available transition variants = https://theme-next.js.org/animate/
[motion.transition]
postBlock = "fadeIn"
postHeader = "fadeInDown"
postBody = "fadeInDown"
collHeader = "fadeInLeft"
# ä¾§è¾¹æ ·æ•ˆæœ åªæœ‰åœ¨ Pisces | Gemini æ¨¡å¼ä¸‹æ‰æ”¯æŒ
sidebar = "fadeInUp"

# TODO
# Progress bar in the top during page loading.
# For more information = https://github.com/CodeByZach/pace
[pace]
enable = false
# All available colors: black | blue | green | orange | pink | purple | red | silver | white | yellow
color = "blue"
# All available themes: big-counter | bounce | barber-shop | center-atom | center-circle | center-radar | center-simple
# corner-indicator | fill-left | flat-top | flash | loading-bar | mac-osx | material | minimal
theme = "minimal"

# TODO
# Canvas ribbon
# For more information = https://github.com/hustcc/ribbon.js
[canvasRibbon]
enable = false
size = 300
alpha = 0.6
zIndex = -1

# ---------------------------------------------------------------
# CDN æœåŠ¡ï¼ˆæš‚æ—¶åªæ”¯æŒ unpkg å’Œ cndjsï¼‰
# ---------------------------------------------------------------

[vendors]
# The CDN provider of NexT internal scripts.
# Available values: local | cdn
internal = "local"
# The default CDN provider of third-party plugins.
# Available values: local | cdnjs | unpkg | jsdelivr | staticfile | bootcdn | 7ed | zstatic | zeyao | custom
plugins = "local"
